use std::fs;
use std::path::PathBuf;
use std::process::Command;
use std::time::SystemTime;
use std::sync::Mutex;

static E2E_TEST_MUTEX: Mutex<()> = Mutex::new(());

fn get_temp_dir() -> PathBuf {
    static COUNTER: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);
    let mut dir = std::env::temp_dir();
    let pid = std::process::id();
    let count = COUNTER.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
    let unique_sub = format!(
        "passiveradar_test_{}_{}_{}",
        pid,
        count,
        SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    );
    dir.push(unique_sub);
    fs::create_dir_all(&dir).unwrap();
    dir
}

fn run_e2e_test(
    width: u16,
    height: u16,
    script: &str,
    expected: &[&str],
    unexpected: &[&str],
) {
    let _lock = E2E_TEST_MUTEX.lock().unwrap_or_else(|e| e.into_inner());
    let tmp_dir = get_temp_dir();
    let script_file = tmp_dir.join("script.txt");
    fs::write(&script_file, script).expect("Failed to write script file");

    let out_dir = tmp_dir.join("out");
    fs::create_dir(&out_dir).expect("Failed to create out dir");

    let bin_path = env!("CARGO_BIN_EXE_passiveradar");
    let status = Command::new(bin_path)
        .env("PASSIVERADAR_FINGERPRINTS_DIR", tmp_dir.join("fingerprints").to_str().unwrap())
        .arg("--mode")
        .arg("sim")
        .arg("--test-script")
        .arg(&script_file)
        .arg("--test-out")
        .arg(&out_dir)
        .arg("--width")
        .arg(width.to_string())
        .arg("--height")
        .arg(height.to_string())
        .status()
        .expect("Failed to run binary");

    eprintln!("status: {}, stderr: {:?}", status, std::fs::read_to_string(out_dir.join("..").join("stderr.txt"))); assert!(status.success(), "Binary exited with error status");

    let frame_file = out_dir.join("frame.txt");
    if frame_file.exists() {
        let content = fs::read_to_string(&frame_file).expect("Failed to read frame.txt");
        for exp in expected {
            assert!(
                content.contains(exp),
                "Expected string {:?} not found in dump:\n{}",
                exp,
                content
            );
        }
        for unexp in unexpected {
            assert!(
                !content.contains(unexp),
                "Unexpected string {:?} found in dump:\n{}",
                unexp,
                content
            );
        }
    } else {
        panic!("frame.txt was not generated by the E2E test run!");
    }

    let _ = fs::remove_dir_all(&tmp_dir);
}

macro_rules! define_e2e_test {
    ($name:ident, $width:expr, $height:expr, $script:expr, $expected:expr, $unexpected:expr) => {
        #[test]
        fn $name() {
            run_e2e_test($width, $height, $script, $expected, $unexpected);
        }
    };
}

// =========================================================================
// TIER 1: FEATURE COVERAGE (40 tests)
// =========================================================================

// Feature 1: Responsive width collapse
define_e2e_test!(
    test_width_collapse_80,
    80,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["Waterfall", "Transient Atmospheric"]
);

define_e2e_test!(
    test_width_collapse_99,
    99,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["Waterfall", "Transient Atmospheric"]
);

define_e2e_test!(
    test_width_collapse_100,
    100,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank", "Waterfall", "Transient Atmospheric"],
    &[]
);

define_e2e_test!(
    test_width_collapse_120,
    120,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank", "Waterfall", "Transient Atmospheric"],
    &[]
);

define_e2e_test!(
    test_width_collapse_150,
    150,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank", "Waterfall", "Transient Atmospheric"],
    &[]
);

// Feature 2: Responsive height collapse logs
define_e2e_test!(
    test_height_collapse_logs_28,
    120,
    28,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["System Events Log"]
);

define_e2e_test!(
    test_height_collapse_logs_29,
    120,
    29,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["System Events Log"]
);

define_e2e_test!(
    test_height_collapse_logs_30,
    120,
    30,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank", "System Events Log"],
    &[]
);

define_e2e_test!(
    test_height_collapse_logs_35,
    120,
    35,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank", "System Events Log"],
    &[]
);

define_e2e_test!(
    test_height_collapse_logs_40,
    120,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank", "System Events Log"],
    &[]
);

// Feature 3: Responsive height collapse map
define_e2e_test!(
    test_height_collapse_map_18,
    120,
    18,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["2D Trajectory Map"]
);

define_e2e_test!(
    test_height_collapse_map_19,
    120,
    19,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["2D Trajectory Map"]
);

define_e2e_test!(
    test_height_collapse_map_20,
    120,
    20,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank", "2D Trajectory Map"],
    &[]
);

define_e2e_test!(
    test_height_collapse_map_22,
    120,
    22,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank", "2D Trajectory Map"],
    &[]
);

define_e2e_test!(
    test_height_collapse_map_25,
    120,
    25,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank", "2D Trajectory Map"],
    &[]
);

// Feature 4: Target table sizing and wrapping
define_e2e_test!(
    test_table_wrapping_100,
    100,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &[]
);

define_e2e_test!(
    test_table_wrapping_110,
    110,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &[]
);

define_e2e_test!(
    test_table_wrapping_120,
    120,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &[]
);

define_e2e_test!(
    test_table_wrapping_130,
    130,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &[]
);

define_e2e_test!(
    test_table_wrapping_140,
    140,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &[]
);

// Feature 5: Simulation Controls Pause
define_e2e_test!(
    test_sim_pause_initial,
    120,
    40,
    "TICK 5\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["[PAUSED]"]
);

define_e2e_test!(
    test_sim_pause_toggle,
    120,
    40,
    "KEY space\nTICK 1\nDUMP frame.txt",
    &["[PAUSED]"],
    &[]
);

define_e2e_test!(
    test_sim_pause_double_toggle,
    120,
    40,
    "KEY space\nKEY space\nTICK 5\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["[PAUSED]"]
);

define_e2e_test!(
    test_sim_pause_multi_toggle,
    120,
    40,
    "KEY space\nKEY space\nKEY space\nTICK 1\nDUMP frame.txt",
    &["[PAUSED]"],
    &[]
);

define_e2e_test!(
    test_sim_pause_unpaused,
    120,
    40,
    "TICK 10\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["[PAUSED]"]
);

// Feature 6: Simulation Controls Speed
define_e2e_test!(
    test_sim_speed_up,
    120,
    40,
    "KEY +\nTICK 1\nDUMP frame.txt",
    &["[1.25x]"],
    &[]
);

define_e2e_test!(
    test_sim_speed_double_up,
    120,
    40,
    "KEY +\nKEY +\nTICK 1\nDUMP frame.txt",
    &["[1.50x]"],
    &[]
);

define_e2e_test!(
    test_sim_speed_down,
    120,
    40,
    "KEY -\nTICK 1\nDUMP frame.txt",
    &["[0.75x]"],
    &[]
);

define_e2e_test!(
    test_sim_speed_double_down,
    120,
    40,
    "KEY -\nKEY -\nTICK 1\nDUMP frame.txt",
    &["[0.50x]"],
    &[]
);

define_e2e_test!(
    test_sim_speed_reset,
    120,
    40,
    "KEY +\nKEY -\nTICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["[1.25x]", "[0.75x]"]
);

// Feature 7: Target Selection and Navigation
define_e2e_test!(
    test_target_select_down,
    120,
    60,
    "TICK 35\nKEY down\nTICK 1\nDUMP frame.txt",
    &["Inspection & EKF State"],
    &[]
);

define_e2e_test!(
    test_target_select_up,
    120,
    60,
    "TICK 35\nKEY down\nKEY up\nKEY down\nTICK 1\nDUMP frame.txt",
    &["Inspection & EKF State"],
    &[]
);

define_e2e_test!(
    test_target_select_esc,
    120,
    60,
    "TICK 35\nKEY down\nKEY esc\nTICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["Inspection & EKF State"]
);

define_e2e_test!(
    test_target_select_nav,
    120,
    60,
    "TICK 35\nKEY down\nKEY down\nTICK 1\nDUMP frame.txt",
    &["Inspection & EKF State"],
    &[]
);

define_e2e_test!(
    test_target_select_inspect,
    120,
    60,
    "TICK 35\nKEY down\nTICK 1\nDUMP frame.txt",
    &["Inspection & EKF State"],
    &[]
);

// Feature 8: Dynamic Visibility Toggles
define_e2e_test!(
    test_panel_toggle_logs,
    120,
    40,
    "KEY l\nTICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["System Events Log"]
);

define_e2e_test!(
    test_panel_toggle_map,
    120,
    40,
    "KEY t\nTICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["2D Trajectory Map"]
);

define_e2e_test!(
    test_panel_toggle_waterfall,
    120,
    40,
    "KEY w\nTICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["Waterfall"]
);

define_e2e_test!(
    test_panel_toggle_logs_on,
    120,
    40,
    "KEY l\nKEY l\nTICK 1\nDUMP frame.txt",
    &["System Events Log"],
    &[]
);

define_e2e_test!(
    test_panel_toggle_all_off,
    120,
    40,
    "KEY l\nKEY t\nKEY w\nTICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["System Events Log", "2D Trajectory Map", "Waterfall"]
);

// =========================================================================
// TIER 2: BOUNDARY & CORNER CASES (40 tests)
// =========================================================================

// Feature 1: Responsive width collapse boundaries
define_e2e_test!(
    test_boundary_width_1,
    1,
    40,
    "TICK 1\nDUMP frame.txt",
    &[""],
    &["Active EKF", "Real-Time Doppler"]
);

define_e2e_test!(
    test_boundary_width_10,
    10,
    40,
    "TICK 1\nDUMP frame.txt",
    &[""],
    &["Active EKF", "Real-Time Doppler"]
);

define_e2e_test!(
    test_boundary_width_50,
    50,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF"],
    &["Real-Time Doppler"]
);

define_e2e_test!(
    test_boundary_width_1000,
    1000,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Waterfall"],
    &[]
);

define_e2e_test!(
    test_boundary_width_99_exact,
    99,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF"],
    &["Waterfall"]
);

// Feature 2: Responsive height collapse logs boundaries
define_e2e_test!(
    test_boundary_height_1,
    120,
    1,
    "TICK 1\nDUMP frame.txt",
    &[""],
    &["System Events Log"]
);

define_e2e_test!(
    test_boundary_height_5,
    120,
    5,
    "TICK 1\nDUMP frame.txt",
    &[""],
    &["System Events Log"]
);

define_e2e_test!(
    test_boundary_height_29_exact,
    120,
    29,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF"],
    &["System Events Log"]
);

define_e2e_test!(
    test_boundary_height_30_exact,
    120,
    30,
    "TICK 1\nDUMP frame.txt",
    &["System Events Log"],
    &[]
);

define_e2e_test!(
    test_boundary_height_1000,
    120,
    1000,
    "TICK 1\nDUMP frame.txt",
    &["System Events Log"],
    &[]
);

// Feature 3: Responsive height collapse map boundaries
define_e2e_test!(
    test_boundary_map_height_1,
    120,
    1,
    "TICK 1\nDUMP frame.txt",
    &[""],
    &["2D Trajectory Map"]
);

define_e2e_test!(
    test_boundary_map_height_10,
    120,
    10,
    "TICK 1\nDUMP frame.txt",
    &[""],
    &["2D Trajectory Map"]
);

define_e2e_test!(
    test_boundary_map_height_19_exact,
    120,
    19,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF"],
    &["2D Trajectory Map"]
);

define_e2e_test!(
    test_boundary_map_height_20_exact,
    120,
    20,
    "TICK 1\nDUMP frame.txt",
    &["2D Trajectory Map"],
    &[]
);

define_e2e_test!(
    test_boundary_map_height_500,
    120,
    500,
    "TICK 1\nDUMP frame.txt",
    &["2D Trajectory Map"],
    &[]
);

// Feature 4: Target table sizing and wrapping boundaries
define_e2e_test!(
    test_boundary_table_wrapping_extremely_narrow,
    58,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &[]
);

define_e2e_test!(
    test_boundary_table_wrapping_very_large,
    500,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &[]
);

define_e2e_test!(
    test_boundary_table_wrapping_exact_limit,
    75,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &[]
);

define_e2e_test!(
    test_boundary_table_wrapping_no_class,
    90,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &[]
);

define_e2e_test!(
    test_boundary_table_wrapping_many_towers,
    120,
    40,
    "TICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &[]
);

// Feature 5: Simulation Controls Pause boundaries
define_e2e_test!(
    test_boundary_sim_pause_during_step,
    120,
    40,
    "KEY space\nKEY s\nTICK 1\nDUMP frame.txt",
    &["[PAUSED]"],
    &[]
);

define_e2e_test!(
    test_boundary_sim_pause_resume_under_high_load,
    120,
    40,
    "KEY space\nKEY space\nKEY space\nKEY space\nTICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["[PAUSED]"]
);

define_e2e_test!(
    test_boundary_sim_pause_step_not_paused,
    120,
    40,
    "KEY s\nTICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["[PAUSED]"]
);

define_e2e_test!(
    test_boundary_sim_pause_multiple_steps,
    120,
    40,
    "KEY space\nKEY s\nKEY s\nTICK 1\nDUMP frame.txt",
    &["[PAUSED]"],
    &[]
);

define_e2e_test!(
    test_boundary_sim_pause_infinite_ticks,
    120,
    40,
    "KEY space\nTICK 10\nDUMP frame.txt",
    &["[PAUSED]"],
    &[]
);

// Feature 6: Simulation Controls Speed boundaries
define_e2e_test!(
    test_boundary_sim_speed_min,
    120,
    40,
    "KEY -\nKEY -\nKEY -\nKEY -\nKEY -\nKEY -\nKEY -\nTICK 1\nDUMP frame.txt",
    &["[0.25x]"],
    &[]
);

define_e2e_test!(
    test_boundary_sim_speed_max,
    120,
    40,
    "KEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nTICK 1\nDUMP frame.txt",
    &["[10.00x]"],
    &[]
);

define_e2e_test!(
    test_boundary_sim_speed_key_overflow,
    120,
    40,
    "KEY -\nKEY -\nKEY -\nKEY -\nKEY -\nKEY -\nKEY -\nKEY -\nKEY -\nKEY -\nTICK 1\nDUMP frame.txt",
    &["[0.25x]"],
    &[]
);

define_e2e_test!(
    test_boundary_sim_speed_key_underflow,
    120,
    40,
    "KEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nTICK 1\nDUMP frame.txt",
    &["[10.00x]"],
    &[]
);

define_e2e_test!(
    test_boundary_sim_speed_saturate_and_reset,
    120,
    40,
    "KEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY -\nTICK 1\nDUMP frame.txt",
    &["[9.75x]"],
    &[]
);

// Feature 7: Target Selection and Navigation boundaries
define_e2e_test!(
    test_boundary_target_select_empty,
    120,
    40,
    "KEY down\nKEY up\nTICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &[">>"]
);

define_e2e_test!(
    test_boundary_target_select_out_of_bounds,
    120,
    40,
    "TICK 35\nKEY down\nKEY down\nKEY down\nKEY down\nTICK 1\nDUMP frame.txt",
    &["Inspection & EKF State"],
    &[]
);

define_e2e_test!(
    test_boundary_target_select_prev_out_of_bounds,
    120,
    40,
    "TICK 35\nKEY down\nKEY up\nTICK 1\nDUMP frame.txt",
    &["Inspection & EKF State"],
    &[]
);

define_e2e_test!(
    test_boundary_target_select_no_selection_press_up,
    120,
    40,
    "TICK 35\nKEY up\nTICK 1\nDUMP frame.txt",
    &["Inspection & EKF State"],
    &[]
);

define_e2e_test!(
    test_boundary_target_select_no_selection_press_down,
    120,
    40,
    "TICK 35\nKEY down\nTICK 1\nDUMP frame.txt",
    &["Inspection & EKF State"],
    &[]
);

// Feature 8: Dynamic Visibility Toggles boundaries
define_e2e_test!(
    test_boundary_panel_toggle_unknown_key,
    120,
    40,
    "KEY x\nTICK 1\nDUMP frame.txt",
    &["System Events Log"],
    &[]
);

define_e2e_test!(
    test_boundary_panel_toggle_all_off_collapsed_width,
    80,
    40,
    "KEY l\nKEY t\nKEY w\nTICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["System Events Log", "2D Trajectory Map"]
);

define_e2e_test!(
    test_boundary_panel_toggle_all_off_collapsed_height,
    120,
    15,
    "KEY l\nKEY t\nKEY w\nTICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["System Events Log", "2D Trajectory Map"]
);

define_e2e_test!(
    test_boundary_panel_toggle_logs_towers_waterfall_all,
    120,
    40,
    "KEY l\nKEY l\nKEY l\nTICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["System Events Log"]
);

define_e2e_test!(
    test_boundary_panel_toggle_rapid,
    120,
    40,
    "KEY w\nKEY w\nKEY t\nKEY t\nTICK 1\nDUMP frame.txt",
    &["Waterfall", "2D Trajectory Map"],
    &[]
);

// =========================================================================
// TIER 3: CROSS-FEATURE COMBINATIONS (8 tests)
// =========================================================================

define_e2e_test!(
    test_combo_width_collapse_and_selection,
    80,
    40,
    "TICK 35\nKEY down\nTICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["Inspection"]
);

define_e2e_test!(
    test_combo_height_collapse_and_toggle,
    120,
    15,
    "KEY l\nKEY t\nTICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["System Events Log", "2D Trajectory Map"]
);

define_e2e_test!(
    test_combo_speed_and_pause,
    120,
    40,
    "KEY +\nKEY +\nKEY space\nTICK 1\nDUMP frame.txt",
    &["[1.50x]", "[PAUSED]"],
    &[]
);

define_e2e_test!(
    test_combo_pause_and_step_selection,
    120,
    40,
    "TICK 30\nKEY space\nKEY s\nKEY s\nKEY s\nKEY s\nKEY s\nKEY down\nTICK 1\nDUMP frame.txt",
    &[">> ", "Inspection & EKF State", "[PAUSED]"],
    &[]
);

define_e2e_test!(
    test_combo_toggle_all_off_and_width_collapse,
    80,
    40,
    "KEY l\nKEY t\nKEY w\nTICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["System Events Log", "2D Trajectory Map", "Waterfall"]
);

define_e2e_test!(
    test_combo_nav_wrap_with_changing_targets,
    120,
    40,
    "TICK 35\nKEY down\nKEY down\nKEY up\nTICK 1\nDUMP frame.txt",
    &[">> ", "Inspection & EKF State"],
    &[]
);

define_e2e_test!(
    test_combo_speed_limits_and_pause,
    120,
    40,
    "KEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY +\nKEY space\nTICK 1\nDUMP frame.txt",
    &["[10.00x]", "[PAUSED]"],
    &[]
);

define_e2e_test!(
    test_combo_wrapping_and_selection,
    100,
    40,
    "TICK 35\nKEY down\nTICK 1\nDUMP frame.txt",
    &[">> ", "Inspection & EKF State"],
    &[]
);

// =========================================================================
// TIER 4: REAL-WORLD APPLICATION SCENARIOS (5 tests)
// =========================================================================

define_e2e_test!(
    test_scenario_normal_operation,
    120,
    40,
    "TICK 20\nDUMP frame.txt",
    &["Waterfall", "System Events Log", "2D Trajectory Map"],
    &[]
);

define_e2e_test!(
    test_scenario_operator_inspection,
    120,
    40,
    "TICK 35\nKEY down\nKEY space\nKEY +\nTICK 1\nDUMP frame.txt",
    &["Inspection & EKF State", "[PAUSED]", "[1.25x]"],
    &[]
);

define_e2e_test!(
    test_scenario_low_spec_terminal,
    80,
    24,
    "KEY t\nTICK 1\nDUMP frame.txt",
    &["Active EKF Tracking Bank"],
    &["Waterfall", "2D Trajectory Map"]
);

define_e2e_test!(
    test_scenario_supersonic_intercept,
    120,
    40,
    "TICK 35\nDUMP frame.txt",
    &["LIVE"],
    &[]
);

define_e2e_test!(
    test_scenario_full_recovery,
    120,
    40,
    "TICK 35\nKEY down\nKEY esc\nKEY l\nKEY space\nKEY -\nTICK 1\nDUMP frame.txt",
    &["[PAUSED]", "[0.75x]"],
    &["System Events Log", "Inspection"]
);
