use std::fs;
use std::path::PathBuf;
use std::process::{Command, Stdio, Child};
use std::thread;
use std::time::{Duration, SystemTime};
use std::sync::Mutex;
use serde_json::json;
use tungstenite::Message;

static WS_TEST_MUTEX: Mutex<()> = Mutex::new(());

struct KillOnDrop(Child);
impl Drop for KillOnDrop {
    fn drop(&mut self) {
        let _ = self.0.kill();
    }
}

fn get_temp_dir() -> PathBuf {
    static COUNTER: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);
    let mut dir = std::env::temp_dir();
    let pid = std::process::id();
    let count = COUNTER.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
    let unique_sub = format!(
        "passiveradar_phase3_4_test_{}_{}_{}",
        pid,
        count,
        SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    );
    dir.push(unique_sub);
    fs::create_dir_all(&dir).unwrap();
    dir
}

fn run_tui_test_with_args(
    width: u16,
    height: u16,
    script: &str,
    expected: &[&str],
    unexpected: &[&str],
    extra_args: &[&str],
) {
    let _lock = WS_TEST_MUTEX.lock().unwrap_or_else(|e| e.into_inner());

    let tmp_dir = get_temp_dir();
    let script_file = tmp_dir.join("script.txt");
    fs::write(&script_file, script).expect("Failed to write script file");

    let out_dir = tmp_dir.join("out");
    fs::create_dir(&out_dir).expect("Failed to create out dir");

    let port = {
        let listener = std::net::TcpListener::bind("127.0.0.1:0").expect("Failed to bind dynamic port");
        listener.local_addr().unwrap().port()
    };

    let bin_path = env!("CARGO_BIN_EXE_passiveradar");
    let mut cmd = Command::new(bin_path);
    cmd.env("PASSIVERADAR_FINGERPRINTS_DIR", tmp_dir.join("fingerprints").to_str().unwrap())
        .arg("--mode")
        .arg("sim")
        .arg("--test-script")
        .arg(&script_file)
        .arg("--test-out")
        .arg(&out_dir)
        .arg("--width")
        .arg(width.to_string())
        .arg("--height")
        .arg(height.to_string())
        .arg("--port")
        .arg(port.to_string());
    
    for arg in extra_args {
        cmd.arg(arg);
    }

    let status = cmd.status().expect("Failed to run binary");

    assert!(status.success(), "Binary exited with error status");

    let frame_file = out_dir.join("frame.txt");
    if frame_file.exists() {
        let content = fs::read_to_string(&frame_file).expect("Failed to read frame.txt");
        for exp in expected {
            assert!(
                content.contains(exp),
                "Expected string {:?} not found in dump:\n{}",
                exp,
                content
            );
        }
        for unexp in unexpected {
            assert!(
                !content.contains(unexp),
                "Unexpected string {:?} found in dump:\n{}",
                unexp,
                content
            );
        }
    } else {
        panic!("frame.txt was not generated by the E2E test run!");
    }

    let _ = fs::remove_dir_all(&tmp_dir);
}

fn run_ws_compound_test(
    script: &str,
    steps: Vec<(serde_json::Value, &str)>,
    extra_args: &[&str],
) {
    let _lock = WS_TEST_MUTEX.lock().unwrap_or_else(|e| e.into_inner());

    let tmp_dir = get_temp_dir();
    let script_file = tmp_dir.join("script.txt");
    fs::write(&script_file, script).expect("Failed to write script file");

    let out_dir = tmp_dir.join("out");
    fs::create_dir(&out_dir).expect("Failed to create out dir");

    let port = {
        let listener = std::net::TcpListener::bind("127.0.0.1:0").expect("Failed to bind dynamic port");
        listener.local_addr().unwrap().port()
    };

    let bin_path = env!("CARGO_BIN_EXE_passiveradar");
    let mut cmd = Command::new(bin_path);
    cmd.env("PASSIVERADAR_FINGERPRINTS_DIR", tmp_dir.join("fingerprints").to_str().unwrap())
        .arg("--mode")
        .arg("sim")
        .arg("--test-script")
        .arg(&script_file)
        .arg("--test-out")
        .arg(&out_dir)
        .arg("--port")
        .arg(port.to_string())
        .stdin(Stdio::null());

    for arg in extra_args {
        cmd.arg(arg);
    }

    let child = cmd.spawn().expect("Failed to spawn passiveradar binary");
    let _child_guard = KillOnDrop(child);
    thread::sleep(Duration::from_millis(400));

    let mut last_err: Option<String> = None;
    let addr: std::net::SocketAddr = format!("127.0.0.1:{}", port).parse().unwrap();
    let ws_url = format!("ws://127.0.0.1:{}", port);
    for _ in 0..15 {
        match std::net::TcpStream::connect_timeout(&addr, Duration::from_millis(200)) {
            Ok(stream) => {
                let _ = stream.set_read_timeout(Some(Duration::from_millis(500)));
                let _ = stream.set_write_timeout(Some(Duration::from_millis(100)));
                
                match tungstenite::client(&ws_url, stream) {
                    Ok((mut socket, _)) => {
                        for (request, expected_substring) in steps {
                            let req_text = serde_json::to_string(&request).unwrap();
                            if let Err(e) = socket.send(Message::Text(req_text.into())) {
                                panic!("Send error in compound test: {:?}", e);
                            }

                            let mut response_found = false;
                            let mut consecutive_would_block = 0;
                            for _ in 0..1000 {
                                match socket.read() {
                                    Ok(Message::Text(text)) => {
                                        consecutive_would_block = 0;
                                        if text.contains(expected_substring) {
                                            response_found = true;
                                            break;
                                        }
                                    }
                                    Ok(Message::Binary(bin)) => {
                                        consecutive_would_block = 0;
                                        // If looking for binary PCM values, we can cast or search hex representation
                                        let hex = bin.iter().map(|b| format!("{:02x}", b)).collect::<Vec<String>>().join("");
                                        if hex.contains(expected_substring) || expected_substring == "binary_data" {
                                            response_found = true;
                                            break;
                                        }
                                    }
                                    Ok(_) => {
                                        consecutive_would_block = 0;
                                    }
                                    Err(e) => {
                                        let err_str = format!("{:?}", e);
                                        if err_str.contains("WouldBlock") || err_str.contains("TimedOut") || err_str.contains("timed out") {
                                            consecutive_would_block += 1;
                                            if consecutive_would_block > 250 {
                                                break;
                                            }
                                            thread::sleep(Duration::from_millis(10));
                                        } else {
                                            break;
                                        }
                                    }
                                }
                            }

                            if !response_found {
                                panic!("Failed to find expected substring {:?} in compound test step", expected_substring);
                            }
                        }
                        let _ = fs::remove_dir_all(&tmp_dir);
                        return;
                    }
                    Err(e) => {
                        last_err = Some(format!("Handshake error: {:?}", e));
                    }
                }
            }
            Err(e) => {
                last_err = Some(format!("Tcp connect error: {:?}", e));
            }
        }
        thread::sleep(Duration::from_millis(300));
    }
    panic!("Failed to verify compound WebSocket server response: {:?}", last_err);
}

// =========================================================================
// TIER 1: FEATURE COVERAGE (5 cases per feature * 8 features = 40 cases)
// =========================================================================

// Feature 1: Continuous Phase Unwrapping
#[test]
fn test_t1_phase_unwrap_normal() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetUnwrapMode", "enabled": true}), "\"unwrapping\": true"),
        (json!({"command": "InjectRawIq", "i": 0.5, "q": 0.5}), "\"displacement\":"),
    ], &[]);
}

#[test]
fn test_t1_phase_unwrap_positive_wrap() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetUnwrapMode", "enabled": true}), "\"unwrapping\": true"),
        (json!({"command": "InjectRawIqSequence", "phases": [3.0, 3.1, -3.1, -3.0]}), "\"unwrapped_phase\": 3.3"),
    ], &[]);
}

#[test]
fn test_t1_phase_unwrap_negative_wrap() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetUnwrapMode", "enabled": true}), "\"unwrapping\": true"),
        (json!({"command": "InjectRawIqSequence", "phases": [-3.0, -3.1, 3.1, 3.0]}), "\"unwrapped_phase\": -3.3"),
    ], &[]);
}

#[test]
fn test_t1_phase_unwrap_waveform() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetUnwrapMode", "enabled": true}), "\"unwrapping\": true"),
        (json!({"command": "InjectSinusoidalDisplacement", "freq": 1.0, "amp": 2.0}), "\"displacement\":"),
    ], &[]);
}

#[test]
fn test_t1_phase_unwrap_ws_sync() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetUnwrapMode", "enabled": true}), "\"unwrapping\": true"),
        (json!({"command": "GetUnwrapStatus"}), "\"enabled\": true"),
    ], &[]);
}

// Feature 2: Cepstral Analysis
#[test]
fn test_t1_cepstrum_rpm_detection() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetCepstrumMode", "enabled": true}), "\"cepstrum_enabled\": true"),
        (json!({"command": "InjectHarmonicSignal", "fundamental_hz": 40.0, "harmonics": [80.0, 120.0, 160.0]}), "\"fundamental_rpm\": 2400.0"),
    ], &[]);
}

#[test]
fn test_t1_cepstrum_magnitude() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetCepstrumMode", "enabled": true}), "\"cepstrum_enabled\": true"),
        (json!({"command": "GetCepstrumData"}), "\"cepstrum_magnitude\":"),
    ], &[]);
}

#[test]
fn test_t1_cepstrum_dynamic_tracking() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetCepstrumMode", "enabled": true}), "\"cepstrum_enabled\": true"),
        (json!({"command": "InjectHarmonicSignal", "fundamental_hz": 40.0}), "\"fundamental_rpm\": 2400.0"),
        (json!({"command": "InjectHarmonicSignal", "fundamental_hz": 50.0}), "\"fundamental_rpm\": 3000.0"),
    ], &[]);
}

#[test]
fn test_t1_cepstrum_ws_sync() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetCepstrumMode", "enabled": true}), "\"cepstrum_enabled\": true"),
        (json!({"command": "GetCepstrumStatus"}), "\"enabled\": true"),
    ], &[]);
}

#[test]
fn test_t1_cepstrum_harmonic_collapse() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetCepstrumMode", "enabled": true}), "\"cepstrum_enabled\": true"),
        (json!({"command": "InjectHarmonicSignal", "fundamental_hz": 30.0, "harmonics": [60.0, 90.0, 120.0, 150.0]}), "\"collapsed_peaks_count\": 1"),
    ], &[]);
}

// Feature 3: Programmable CIC Decimation Banks
#[test]
fn test_t1_cic_seismic_mode() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetVibrometerMode", "mode": "Seismic"}), "\"mode\": \"Seismic\""),
        (json!({"command": "GetVibrometerConfig"}), "\"frequency_min\": 0.01, \"frequency_max\": 5.0"),
    ], &[]);
}

#[test]
fn test_t1_cic_rotary_mode() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetVibrometerMode", "mode": "Rotary"}), "\"mode\": \"Rotary\""),
        (json!({"command": "GetVibrometerConfig"}), "\"frequency_min\": 10.0, \"frequency_max\": 250.0"),
    ], &[]);
}

#[test]
fn test_t1_cic_acoustic_mode() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetVibrometerMode", "mode": "Acoustic"}), "\"mode\": \"Acoustic\""),
        (json!({"command": "GetVibrometerConfig"}), "\"frequency_min\": 300.0, \"frequency_max\": 4000.0"),
    ], &[]);
}

#[test]
fn test_t1_cic_mode_switching() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetVibrometerMode", "mode": "Seismic"}), "\"mode\": \"Seismic\""),
        (json!({"command": "SetVibrometerMode", "mode": "Rotary"}), "\"mode\": \"Rotary\""),
    ], &[]);
}

#[test]
fn test_t1_cic_telemetry() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetVibrometerMode", "mode": "Acoustic"}), "\"mode\": \"Acoustic\""),
        (json!({"command": "GetTelemetry"}), "\"vibrometer_mode\": \"Acoustic\""),
    ], &[]);
}

// Feature 4: Deep-Integration Master EKF
#[test]
fn test_t1_ekf_state_init() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetMasterEkf", "enabled": true}), "\"master_ekf\": true"),
        (json!({"command": "GetMasterEkfState"}), "\"state_dim\": 6"),
    ], &[]);
}

#[test]
fn test_t1_ekf_multi_tower() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetMasterEkf", "enabled": true}), "\"master_ekf\": true"),
        (json!({"command": "InjectTowerPeakErrors", "errors": [{"tower": "T1", "phase_error": 0.05}, {"tower": "T2", "phase_error": -0.02}]}), "\"updated\": true"),
    ], &[]);
}

#[test]
fn test_t1_ekf_predict_propagation() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetMasterEkf", "enabled": true}), "\"master_ekf\": true"),
        (json!({"command": "PropagateMasterEkf", "dt": 0.1}), "\"cov_expanded\": true"),
    ], &[]);
}

#[test]
fn test_t1_ekf_convergence() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetMasterEkf", "enabled": true}), "\"master_ekf\": true"),
        (json!({"command": "RunConvergenceBenchmark"}), "\"master_ekf_converged\": true"),
    ], &[]);
}

#[test]
fn test_t1_ekf_stability() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetMasterEkf", "enabled": true}), "\"master_ekf\": true"),
        (json!({"command": "GetMasterEkfStability"}), "\"stable\": true"),
    ], &[]);
}

// Feature 5: Wi-Fi Respiration Tracker
#[test]
fn test_t1_wifi_multipath_cancellation() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "WifiRespiration", "enabled": true}), "\"omni_mode\": \"WifiRespiration\""),
        (json!({"command": "VerifyStaticMultipathCancellation"}), "\"clutter_suppression_db\":"),
    ], &[]);
}

#[test]
fn test_t1_wifi_spike_pruning() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "WifiRespiration", "enabled": true}), "\"omni_mode\": \"WifiRespiration\""),
        (json!({"command": "VerifySpikePruning"}), "\"spikes_pruned\":"),
    ], &[]);
}

#[test]
fn test_t1_wifi_breathing_extraction() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "WifiRespiration", "enabled": true}), "\"omni_mode\": \"WifiRespiration\""),
        (json!({"command": "InjectBreathingSignal", "rate_hz": 0.3}), "\"breathing_rate_hz\": 0.3"),
    ], &[]);
}

#[test]
fn test_t1_wifi_ws_sync() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "WifiRespiration", "enabled": true}), "\"omni_mode\": \"WifiRespiration\""),
        (json!({"command": "GetOmniModeStatus"}), "\"active_mode\": \"WifiRespiration\""),
    ], &[]);
}

#[test]
fn test_t1_wifi_telemetry() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "WifiRespiration", "enabled": true}), "\"omni_mode\": \"WifiRespiration\""),
        (json!({"command": "GetTelemetry"}), "\"occupancy_confidence\":"),
    ], &[]);
}

// Feature 6: Ghost Mic
#[test]
fn test_t1_ghost_mic_displacement() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "GhostMic", "enabled": true}), "\"omni_mode\": \"GhostMic\""),
        (json!({"command": "GetTelemetry"}), "\"displacement_source\": \"Acoustic\""),
    ], &[]);
}

#[test]
fn test_t1_ghost_mic_pcm_format() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "GhostMic", "enabled": true}), "\"omni_mode\": \"GhostMic\""),
        (json!({"command": "GetGhostMicFormat"}), "\"format\": \"pcm_s16le\""),
    ], &[]);
}

#[test]
fn test_t1_ghost_mic_ws_stream() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "GhostMic", "enabled": true}), "\"omni_mode\": \"GhostMic\""),
        (json!({"command": "StartAudioStreaming"}), "\"streaming\": true"),
    ], &[]);
}

#[test]
fn test_t1_ghost_mic_controls() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "GhostMic", "enabled": true}), "\"omni_mode\": \"GhostMic\""),
        (json!({"command": "SetGhostMicGain", "gain": 2.0}), "\"gain\": 2.0"),
    ], &[]);
}

#[test]
fn test_t1_ghost_mic_scaling() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "GhostMic", "enabled": true}), "\"omni_mode\": \"GhostMic\""),
        (json!({"command": "InjectWindowVibration", "amplitude": 1e-3}), "\"amplitude_scale\":"),
    ], &[]);
}

// Feature 7: Stare Mode
#[test]
fn test_t1_stare_velocity_lock() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetStareMode", "latitude": 47.6, "longitude": -122.3, "altitude": 100.0}), "\"stare_mode\": true"),
        (json!({"command": "GetTelemetry"}), "\"velocity\": [0.0,0.0,0.0]"),
    ], &[]);
}

#[test]
fn test_t1_stare_spectra_output() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetStareMode", "latitude": 47.6, "longitude": -122.3, "altitude": 100.0}), "\"stare_mode\": true"),
        (json!({"command": "GetVibrationSpectra"}), "\"spectra\":"),
    ], &[]);
}

#[test]
fn test_t1_stare_activation() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetStareMode", "latitude": 47.6, "longitude": -122.3, "altitude": 100.0}), "\"stare_mode\": true"),
        (json!({"command": "GetStareStatus"}), "\"active\": true"),
    ], &[]);
}

#[test]
fn test_t1_stare_resonance_map() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetStareMode", "latitude": 47.6, "longitude": -122.3, "altitude": 100.0}), "\"stare_mode\": true"),
        (json!({"command": "VerifyResonancePeaks"}), "\"resonances\":"),
    ], &[]);
}

#[test]
fn test_t1_stare_continuous_status() {
    run_ws_compound_test("TICK 500", vec![
        (json!({"command": "SetStareMode", "latitude": 47.6, "longitude": -122.3, "altitude": 100.0}), "\"stare_mode\": true"),
        (json!({"command": "GetStareStatus"}), "\"active\": true"),
    ], &[]);
}

// Feature 8: Drone Payload Heuristics
#[test]
fn test_t1_drone_thrust_estimation() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "InjectDroneTarget", "rpm": 6000.0, "vz": 2.0}), "\"thrust_to_weight\":"),
    ], &[]);
}

#[test]
fn test_t1_drone_payload_classification() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "InjectDroneTarget", "rpm": 8000.0, "vz": 0.5}), "\"payload_class\": \"Heavy\""),
    ], &[]);
}

#[test]
fn test_t1_drone_ws_sync() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "InjectDroneTarget", "rpm": 5000.0, "vz": 0.0}), "\"drone_heuristics_active\": true"),
    ], &[]);
}

#[test]
fn test_t1_drone_negative_climb() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "InjectDroneTarget", "rpm": 4000.0, "vz": -2.0}), "\"thrust_to_weight\":"),
    ], &[]);
}

#[test]
fn test_t1_drone_dynamic_payload() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "InjectDroneTarget", "rpm": 5000.0, "vz": 0.0}), "\"payload_class\": \"Light\""),
        (json!({"command": "InjectDroneTarget", "rpm": 8500.0, "vz": 0.0}), "\"payload_class\": \"Heavy\""),
    ], &[]);
}

// =========================================================================
// TIER 2: BOUNDARY & CORNER CASES (5 cases per feature * 8 features = 40 cases)
// =========================================================================

// Feature 1: Continuous Phase Unwrapping Boundaries
#[test]
fn test_t2_unwrap_extreme_jump() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetUnwrapMode", "enabled": true}), "\"unwrapping\": true"),
        (json!({"command": "InjectRawIqSequence", "phases": [0.0, 3.5, -3.5, 0.0]}), "\"unwrapped_phase\":"),
    ], &[]);
}

#[test]
fn test_t2_unwrap_zero_signal() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetUnwrapMode", "enabled": true}), "\"unwrapping\": true"),
        (json!({"command": "InjectRawIq", "i": 0.0, "q": 0.0}), "\"displacement\": 0.0"),
    ], &[]);
}

#[test]
fn test_t2_unwrap_nan_recovery() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetUnwrapMode", "enabled": true}), "\"unwrapping\": true"),
        (json!({"command": "InjectRawIq", "i": std::f64::NAN, "q": 0.0}), "\"error\":"),
        (json!({"command": "InjectRawIq", "i": 1.0, "q": 0.0}), "\"displacement\":"),
    ], &[]);
}

#[test]
fn test_t2_unwrap_rapid_oscillation() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetUnwrapMode", "enabled": true}), "\"unwrapping\": true"),
        (json!({"command": "InjectRawIqSequence", "phases": [3.1, -3.1, 3.1, -3.1, 3.1]}), "\"displacement\":"),
    ], &[]);
}

#[test]
fn test_t2_unwrap_long_run_overflow() {
    run_ws_compound_test("TICK 1000", vec![
        (json!({"command": "SetUnwrapMode", "enabled": true}), "\"unwrapping\": true"),
        (json!({"command": "InjectMonotonicPhaseGrowth", "steps": 5000}), "\"overflow\": false"),
    ], &[]);
}

// Feature 2: Cepstral Analysis Boundaries
#[test]
fn test_t2_cepstrum_no_harmonics() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetCepstrumMode", "enabled": true}), "\"cepstrum_enabled\": true"),
        (json!({"command": "InjectHarmonicSignal", "fundamental_hz": 40.0, "harmonics": []}), "\"fundamental_rpm\": 0.0"),
    ], &[]);
}

#[test]
fn test_t2_cepstrum_high_frequency() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetCepstrumMode", "enabled": true}), "\"cepstrum_enabled\": true"),
        (json!({"command": "InjectHarmonicSignal", "fundamental_hz": 10000.0}), "\"error\":"),
    ], &[]);
}

#[test]
fn test_t2_cepstrum_noise_only() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetCepstrumMode", "enabled": true}), "\"cepstrum_enabled\": true"),
        (json!({"command": "InjectNoiseOnlySignal"}), "\"fundamental_rpm\": 0.0"),
    ], &[]);
}

#[test]
fn test_t2_cepstrum_negative_freq() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetCepstrumMode", "enabled": true}), "\"cepstrum_enabled\": true"),
        (json!({"command": "InjectHarmonicSignal", "fundamental_hz": -40.0}), "\"error\":"),
    ], &[]);
}

#[test]
fn test_t2_cepstrum_dense_peaks() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetCepstrumMode", "enabled": true}), "\"cepstrum_enabled\": true"),
        (json!({"command": "InjectDualRotaryHarmonics", "f1": 30.0, "f2": 35.0}), "\"peaks\":"),
    ], &[]);
}

// Feature 3: CIC Decimation Bank Boundaries
#[test]
fn test_t2_cic_bypass() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetVibrometerMode", "mode": "Bypass"}), "\"mode\": \"Bypass\""),
        (json!({"command": "GetVibrometerConfig"}), "\"decimation_factor\": 1"),
    ], &[]);
}

#[test]
fn test_t2_cic_large_factor() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetVibrometerMode", "mode": "Seismic", "decimation_factor": 1000000}), "\"error\":"),
    ], &[]);
}

#[test]
fn test_t2_cic_rapid_toggling() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetVibrometerMode", "mode": "Seismic"}), "\"mode\": \"Seismic\""),
        (json!({"command": "SetVibrometerMode", "mode": "Rotary"}), "\"mode\": \"Rotary\""),
        (json!({"command": "SetVibrometerMode", "mode": "Acoustic"}), "\"mode\": \"Acoustic\""),
        (json!({"command": "SetVibrometerMode", "mode": "Seismic"}), "\"mode\": \"Seismic\""),
    ], &[]);
}

#[test]
fn test_t2_cic_amplitude_overflow() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetVibrometerMode", "mode": "Seismic"}), "\"mode\": \"Seismic\""),
        (json!({"command": "InjectExtremeAmplitudeSignal", "val": 1e12}), "\"overflow_handled\": true"),
    ], &[]);
}

#[test]
fn test_t2_cic_zero_input() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetVibrometerMode", "mode": "Seismic"}), "\"mode\": \"Seismic\""),
        (json!({"command": "InjectRawIq", "i": 0.0, "q": 0.0}), "\"displacement\": 0.0"),
    ], &[]);
}

// Feature 4: Deep-Integration Master EKF Boundaries
#[test]
fn test_t2_ekf_zero_towers() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetMasterEkf", "enabled": true}), "\"master_ekf\": true"),
        (json!({"command": "ClearActiveTowers"}), "\"towers_count\": 0"),
        (json!({"command": "PropagateMasterEkf", "dt": 0.1}), "\"cov_expanded\": true"),
    ], &[]);
}

#[test]
fn test_t2_ekf_extreme_outliers() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetMasterEkf", "enabled": true}), "\"master_ekf\": true"),
        (json!({"command": "InjectTowerPeakErrors", "errors": [{"tower": "T1", "phase_error": 1e9}]}), "\"outlier_rejected\": true"),
    ], &[]);
}

#[test]
fn test_t2_ekf_origin_singularity() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetMasterEkf", "enabled": true}), "\"master_ekf\": true"),
        (json!({"command": "InjectMasterEkfTarget", "pos": [0.0, 0.0, 0.0]}), "\"singularity_avoided\": true"),
    ], &[]);
}

#[test]
fn test_t2_ekf_superluminal_speed() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetMasterEkf", "enabled": true}), "\"master_ekf\": true"),
        (json!({"command": "InjectMasterEkfTarget", "vel": [4e8, 0.0, 0.0]}), "\"error\":"),
    ], &[]);
}

#[test]
fn test_t2_ekf_covariance_symmetry() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetMasterEkf", "enabled": true}), "\"master_ekf\": true"),
        (json!({"command": "VerifyCovarianceSymmetry"}), "\"symmetric\": true, \"positive_definite\": true"),
    ], &[]);
}

// Feature 5: Wi-Fi Respiration Boundaries
#[test]
fn test_t2_wifi_packet_burst() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "WifiRespiration", "enabled": true}), "\"omni_mode\": \"WifiRespiration\""),
        (json!({"command": "InjectWifiPacketBurst", "packet_count": 10000}), "\"buffer_overflow\": false"),
    ], &[]);
}

#[test]
fn test_t2_wifi_zero_rate() {
    run_ws_compound_test("TICK 500", vec![
        (json!({"command": "SetOmniMode", "mode": "WifiRespiration", "enabled": true}), "\"omni_mode\": \"WifiRespiration\""),
        (json!({"command": "InjectWifiPacketBurst", "packet_count": 0}), "\"suspended\": true"),
    ], &[]);
}

#[test]
fn test_t2_wifi_multipath_saturation() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "WifiRespiration", "enabled": true}), "\"omni_mode\": \"WifiRespiration\""),
        (json!({"command": "InjectMultipathClutter", "clutter_db": 60.0}), "\"clutter_suppressed\": true"),
    ], &[]);
}

#[test]
fn test_t2_wifi_non_human_frequency() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "WifiRespiration", "enabled": true}), "\"omni_mode\": \"WifiRespiration\""),
        (json!({"command": "InjectBreathingSignal", "rate_hz": 12.0}), "\"breathing_rate_hz\": 0.0"),
    ], &[]);
}

#[test]
fn test_t2_wifi_rapid_movement() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "WifiRespiration", "enabled": true}), "\"omni_mode\": \"WifiRespiration\""),
        (json!({"command": "InjectTransientMovement"}), "\"occupancy_confidence\":"),
    ], &[]);
}

// Feature 6: Ghost Mic Boundaries
#[test]
fn test_t2_ghost_mic_buffer_overflow() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "GhostMic", "enabled": true}), "\"omni_mode\": \"GhostMic\""),
        (json!({"command": "SimulateSlowClient", "delay_ms": 200}), "\"dropped_packets\":"),
    ], &[]);
}

#[test]
fn test_t2_ghost_mic_clipping() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "GhostMic", "enabled": true}), "\"omni_mode\": \"GhostMic\""),
        (json!({"command": "InjectWindowVibration", "amplitude": 5.0}), "\"clipping_occurred\": true"),
    ], &[]);
}

#[test]
fn test_t2_ghost_mic_silence() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "GhostMic", "enabled": true}), "\"omni_mode\": \"GhostMic\""),
        (json!({"command": "InjectWindowVibration", "amplitude": 0.0}), "\"displacement\": 0.0"),
    ], &[]);
}

#[test]
fn test_t2_ghost_mic_reconnect() {
    run_ws_compound_test("TICK 200", vec![
        (json!({"command": "SetOmniMode", "mode": "GhostMic", "enabled": true}), "\"omni_mode\": \"GhostMic\""),
        (json!({"command": "ReconnectAudioSocket"}), "\"reconnected\": true"),
    ], &[]);
}

#[test]
fn test_t2_ghost_mic_command_bounds() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetGhostMicGain", "gain": -1.5}), "\"error\":"),
    ], &[]);
}

// Feature 7: Stare Mode Boundaries
#[test]
fn test_t2_stare_out_of_bounds() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetStareMode", "latitude": 95.0, "longitude": 200.0, "altitude": 0.0}), "\"error\":"),
    ], &[]);
}

#[test]
fn test_t2_stare_moving_target() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetStareMode", "latitude": 47.6, "longitude": -122.3, "altitude": 100.0}), "\"stare_mode\": true"),
        (json!({"command": "InjectMovingTarget", "speed": 150.0}), "\"target_velocity\": [0.0,0.0,0.0]"),
    ], &[]);
}

#[test]
fn test_t2_stare_tower_dropout() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetStareMode", "latitude": 47.6, "longitude": -122.3, "altitude": 100.0}), "\"stare_mode\": true"),
        (json!({"command": "ClearActiveTowers"}), "\"towers_count\": 0"),
        (json!({"command": "GetStareStatus"}), "\"active\": true"),
    ], &[]);
}

#[test]
fn test_t2_stare_noise_only() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetStareMode", "latitude": 47.6, "longitude": -122.3, "altitude": 100.0}), "\"stare_mode\": true"),
        (json!({"command": "InjectNoiseOnlySignal"}), "\"vibration_spectra\":"),
    ], &[]);
}

#[test]
fn test_t2_stare_overlapping_targets() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetStareMode", "latitude": 47.6, "longitude": -122.3, "altitude": 100.0}), "\"stare_mode\": true"),
        (json!({"command": "InjectDualOverlappingTargets"}), "\"stare_target_isolated\": true"),
    ], &[]);
}

// Feature 8: Drone Payload Heuristics Boundaries
#[test]
fn test_t2_drone_descending() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "InjectDroneTarget", "rpm": 3000.0, "vz": -5.0}), "\"thrust_to_weight\":"),
    ], &[]);
}

#[test]
fn test_t2_drone_supersonic_rpm() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "InjectDroneTarget", "rpm": 120000.0, "vz": 1.0}), "\"error\":"),
    ], &[]);
}

#[test]
fn test_t2_drone_missing_sidebands() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "InjectDroneTarget", "vz": 1.0}), "\"thrust_to_weight\": 1.0"),
    ], &[]);
}

#[test]
fn test_t2_drone_incompatible_state() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "InjectDroneTarget", "rpm": 9000.0, "vz": 0.0}), "\"payload_class\": \"Heavy\""),
    ], &[]);
}

#[test]
fn test_t2_drone_high_sideband_noise() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "InjectDroneTargetWithNoise", "rpm": 6000.0, "vz": 0.0, "noise_db": 10.0}), "\"payload_class\":"),
    ], &[]);
}

// =========================================================================
// TIER 3: CROSS-FEATURE COMBINATIONS (8 cases)
// =========================================================================

#[test]
fn test_t3_stare_seismic_unwrap() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetStareMode", "latitude": 47.6, "longitude": -122.3, "altitude": 100.0}), "\"stare_mode\": true"),
        (json!({"command": "SetVibrometerMode", "mode": "Seismic"}), "\"mode\": \"Seismic\""),
        (json!({"command": "SetUnwrapMode", "enabled": true}), "\"unwrapping\": true"),
        (json!({"command": "GetTelemetry"}), "\"displacement\":"),
    ], &[]);
}

#[test]
fn test_t3_wifi_master_ekf() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "WifiRespiration", "enabled": true}), "\"omni_mode\": \"WifiRespiration\""),
        (json!({"command": "SetMasterEkf", "enabled": true}), "\"master_ekf\": true"),
        (json!({"command": "GetTelemetry"}), "\"master_ekf_state\":"),
    ], &[]);
}

#[test]
fn test_t3_ghost_mic_acoustic_unwrap() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetVibrometerMode", "mode": "Acoustic"}), "\"mode\": \"Acoustic\""),
        (json!({"command": "SetUnwrapMode", "enabled": true}), "\"unwrapping\": true"),
        (json!({"command": "SetOmniMode", "mode": "GhostMic", "enabled": true}), "\"omni_mode\": \"GhostMic\""),
        (json!({"command": "GetTelemetry"}), "\"pcm_stream_active\": true"),
    ], &[]);
}

#[test]
fn test_t3_drone_cepstrum_heuristics() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetCepstrumMode", "enabled": true}), "\"cepstrum_enabled\": true"),
        (json!({"command": "InjectHarmonicSignal", "fundamental_hz": 50.0}), "\"fundamental_rpm\": 3000.0"),
        (json!({"command": "InjectDroneTarget", "rpm": 3000.0, "vz": 1.0}), "\"thrust_to_weight\":"),
    ], &[]);
}

#[test]
fn test_t3_stare_rotary_cepstrum() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetStareMode", "latitude": 47.6, "longitude": -122.3, "altitude": 100.0}), "\"stare_mode\": true"),
        (json!({"command": "SetVibrometerMode", "mode": "Rotary"}), "\"mode\": \"Rotary\""),
        (json!({"command": "SetCepstrumMode", "enabled": true}), "\"cepstrum_enabled\": true"),
        (json!({"command": "GetTelemetry"}), "\"fundamental_rpm\":"),
    ], &[]);
}

#[test]
fn test_t3_wifi_ghost_mic_coexistence() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetOmniMode", "mode": "WifiRespiration", "enabled": true}), "\"omni_mode\": \"WifiRespiration\""),
        (json!({"command": "SetOmniMode", "mode": "GhostMic", "enabled": true}), "\"omni_mode\": \"GhostMic\""),
        (json!({"command": "GetTelemetry"}), "\"occupancy_confidence\":"),
    ], &[]);
}

#[test]
fn test_t3_drone_ekf_stare_hover() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetStareMode", "latitude": 47.6, "longitude": -122.3, "altitude": 100.0}), "\"stare_mode\": true"),
        (json!({"command": "SetMasterEkf", "enabled": true}), "\"master_ekf\": true"),
        (json!({"command": "InjectDroneTarget", "rpm": 6000.0, "vz": 0.0}), "\"payload_class\":"),
    ], &[]);
}

#[test]
fn test_t3_unwrap_cepstrum_acoustic() {
    run_ws_compound_test("TICK 100", vec![
        (json!({"command": "SetVibrometerMode", "mode": "Acoustic"}), "\"mode\": \"Acoustic\""),
        (json!({"command": "SetUnwrapMode", "enabled": true}), "\"unwrapping\": true"),
        (json!({"command": "SetCepstrumMode", "enabled": true}), "\"cepstrum_enabled\": true"),
        (json!({"command": "GetTelemetry"}), "\"fundamental_rpm\":"),
    ], &[]);
}

// =========================================================================
// TIER 4: REAL-WORLD APPLICATION SCENARIOS (5 scenarios)
// =========================================================================

#[test]
fn test_t4_scenario_1_drone_hover_payload() {
    run_ws_compound_test("TICK 200", vec![
        (json!({"command": "SetStareMode", "latitude": 47.6, "longitude": -122.3, "altitude": 100.0}), "\"stare_mode\": true"),
        (json!({"command": "SetMasterEkf", "enabled": true}), "\"master_ekf\": true"),
        (json!({"command": "SetCepstrumMode", "enabled": true}), "\"cepstrum_enabled\": true"),
        (json!({"command": "InjectDroneTarget", "rpm": 8000.0, "vz": 0.0}), "\"payload_class\": \"Heavy\""),
    ], &[]);
}

#[test]
fn test_t4_scenario_2_acoustic_window_eavesdropping() {
    run_ws_compound_test("TICK 200", vec![
        (json!({"command": "SetVibrometerMode", "mode": "Acoustic"}), "\"mode\": \"Acoustic\""),
        (json!({"command": "SetUnwrapMode", "enabled": true}), "\"unwrapping\": true"),
        (json!({"command": "SetOmniMode", "mode": "GhostMic", "enabled": true}), "\"omni_mode\": \"GhostMic\""),
        (json!({"command": "InjectWindowVibrationWithAmbientNoise", "vibe_freq": 1000.0, "noise_db": 30.0}), "\"displacement\":"),
    ], &[]);
}

#[test]
fn test_t4_scenario_3_wifi_breathing_through_wall() {
    run_ws_compound_test("TICK 500", vec![
        (json!({"command": "SetOmniMode", "mode": "WifiRespiration", "enabled": true}), "\"omni_mode\": \"WifiRespiration\""),
        (json!({"command": "InjectWifiSignalThroughWall", "breath_freq": 0.3, "wall_thickness_m": 0.3}), "\"breathing_rate_hz\": 0.3"),
    ], &[]);
}

#[test]
fn test_t4_scenario_4_transformer_magnetostriction() {
    run_ws_compound_test("TICK 300", vec![
        (json!({"command": "SetStareMode", "latitude": 47.6, "longitude": -122.3, "altitude": 100.0}), "\"stare_mode\": true"),
        (json!({"command": "SetVibrometerMode", "mode": "Rotary"}), "\"mode\": \"Rotary\""),
        (json!({"command": "SetCepstrumMode", "enabled": true}), "\"cepstrum_enabled\": true"),
        (json!({"command": "InjectHarmonicSignal", "fundamental_hz": 120.0}), "\"fundamental_rpm\": 7200.0"),
    ], &[]);
}

#[test]
fn test_t4_scenario_5_high_speed_ekf_unwrap() {
    run_ws_compound_test("TICK 200", vec![
        (json!({"command": "SetMasterEkf", "enabled": true}), "\"master_ekf\": true"),
        (json!({"command": "SetUnwrapMode", "enabled": true}), "\"unwrapping\": true"),
        (json!({"command": "InjectMasterEkfTarget", "pos": [1000.0, 2000.0, 500.0], "vel": [600.0, 0.0, 0.0]}), "\"displacement\":"),
    ], &[]);
}
