use std::fs;
use std::path::PathBuf;
use std::process::{Command, Stdio, Child};
use std::thread;
use std::time::{Duration, SystemTime};
use std::sync::Mutex;
use serde_json::json;
use tungstenite::Message;

static WS_TEST_MUTEX: Mutex<()> = Mutex::new(());

struct KillOnDrop(Child);
impl Drop for KillOnDrop {
    fn drop(&mut self) {
        let _ = self.0.kill();
    }
}

fn get_temp_dir() -> PathBuf {
    static COUNTER: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);
    let mut dir = std::env::temp_dir();
    let pid = std::process::id();
    let count = COUNTER.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
    let unique_sub = format!(
        "passiveradar_premium_test_{}_{}_{}",
        pid,
        count,
        SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    );
    dir.push(unique_sub);
    fs::create_dir_all(&dir).unwrap();
    dir
}

fn run_tui_test(
    width: u16,
    height: u16,
    script: &str,
    expected: &[&str],
    unexpected: &[&str],
) {
    run_tui_test_with_args(width, height, script, expected, unexpected, &[]);
}

fn run_tui_test_with_args(
    width: u16,
    height: u16,
    script: &str,
    expected: &[&str],
    unexpected: &[&str],
    extra_args: &[&str],
) {
    let _lock = WS_TEST_MUTEX.lock().unwrap_or_else(|e| e.into_inner());

    let tmp_dir = get_temp_dir();
    let script_file = tmp_dir.join("script.txt");
    fs::write(&script_file, script).expect("Failed to write script file");

    let out_dir = tmp_dir.join("out");
    fs::create_dir(&out_dir).expect("Failed to create out dir");

    let port = {
        let listener = std::net::TcpListener::bind("127.0.0.1:0").expect("Failed to bind dynamic port");
        listener.local_addr().unwrap().port()
    };

    let bin_path = env!("CARGO_BIN_EXE_passiveradar");
    let mut cmd = Command::new(bin_path);
    cmd.env("PASSIVERADAR_FINGERPRINTS_DIR", tmp_dir.join("fingerprints").to_str().unwrap())
        .arg("--mode")
        .arg("sim")
        .arg("--test-script")
        .arg(&script_file)
        .arg("--test-out")
        .arg(&out_dir)
        .arg("--width")
        .arg(width.to_string())
        .arg("--height")
        .arg(height.to_string())
        .arg("--port")
        .arg(port.to_string());
    
    for arg in extra_args {
        cmd.arg(arg);
    }

    let status = cmd.status().expect("Failed to run binary");

    assert!(status.success(), "Binary exited with error status");

    let frame_file = out_dir.join("frame.txt");
    if frame_file.exists() {
        let content = fs::read_to_string(&frame_file).expect("Failed to read frame.txt");
        for exp in expected {
            assert!(
                content.contains(exp),
                "Expected string {:?} not found in dump:\n{}",
                exp,
                content
            );
        }
        for unexp in unexpected {
            assert!(
                !content.contains(unexp),
                "Unexpected string {:?} found in dump:\n{}",
                unexp,
                content
            );
        }
    } else {
        panic!("frame.txt was not generated by the E2E test run!");
    }

    let _ = fs::remove_dir_all(&tmp_dir);
}

fn run_tui_test_toggle(
    width: u16,
    height: u16,
    script: &str,
    expected_before: &[&str],
    expected_after: &[&str],
    unexpected_after: &[&str],
) {
    run_tui_test_toggle_with_args(width, height, script, expected_before, expected_after, unexpected_after, &[]);
}

fn run_tui_test_toggle_with_args(
    width: u16,
    height: u16,
    script: &str,
    expected_before: &[&str],
    expected_after: &[&str],
    unexpected_after: &[&str],
    extra_args: &[&str],
) {
    let _lock = WS_TEST_MUTEX.lock().unwrap_or_else(|e| e.into_inner());

    let tmp_dir = get_temp_dir();
    let script_file = tmp_dir.join("script.txt");
    fs::write(&script_file, script).expect("Failed to write script file");

    let out_dir = tmp_dir.join("out");
    fs::create_dir(&out_dir).expect("Failed to create out dir");

    let port = {
        let listener = std::net::TcpListener::bind("127.0.0.1:0").expect("Failed to bind dynamic port");
        listener.local_addr().unwrap().port()
    };

    let bin_path = env!("CARGO_BIN_EXE_passiveradar");
    let mut cmd = Command::new(bin_path);
    cmd.env("PASSIVERADAR_FINGERPRINTS_DIR", tmp_dir.join("fingerprints").to_str().unwrap())
        .arg("--mode")
        .arg("sim")
        .arg("--test-script")
        .arg(&script_file)
        .arg("--test-out")
        .arg(&out_dir)
        .arg("--width")
        .arg(width.to_string())
        .arg("--height")
        .arg(height.to_string())
        .arg("--port")
        .arg(port.to_string());
    
    for arg in extra_args {
        cmd.arg(arg);
    }

    let status = cmd.status().expect("Failed to run binary");

    assert!(status.success(), "Binary exited with error status");

    let before_file = out_dir.join("frame_before.txt");
    if before_file.exists() {
        let content = fs::read_to_string(&before_file).expect("Failed to read frame_before.txt");
        for exp in expected_before {
            assert!(
                content.contains(exp),
                "Expected string {:?} not found in before dump:\n{}",
                exp,
                content
            );
        }
    } else {
        panic!("frame_before.txt was not generated by the E2E test run!");
    }

    let frame_file = out_dir.join("frame.txt");
    if frame_file.exists() {
        let content = fs::read_to_string(&frame_file).expect("Failed to read frame.txt");
        for exp in expected_after {
            assert!(
                content.contains(exp),
                "Expected string {:?} not found in after dump:\n{}",
                exp,
                content
            );
        }
        for unexp in unexpected_after {
            assert!(
                !content.contains(unexp),
                "Unexpected string {:?} found in after dump:\n{}",
                unexp,
                content
            );
        }
    } else {
        panic!("frame.txt was not generated by the E2E test run!");
    }

    let _ = fs::remove_dir_all(&tmp_dir);
}

fn run_ws_compound_test(
    script: &str,
    steps: Vec<(serde_json::Value, &str)>,
) {
    let _lock = WS_TEST_MUTEX.lock().unwrap_or_else(|e| e.into_inner());

    let tmp_dir = get_temp_dir();
    let script_file = tmp_dir.join("script.txt");
    fs::write(&script_file, script).expect("Failed to write script file");

    let out_dir = tmp_dir.join("out");
    fs::create_dir(&out_dir).expect("Failed to create out dir");

    let port = {
        let listener = std::net::TcpListener::bind("127.0.0.1:0").expect("Failed to bind dynamic port");
        listener.local_addr().unwrap().port()
    };

    let bin_path = env!("CARGO_BIN_EXE_passiveradar");
    let child = Command::new(bin_path)
        .env("PASSIVERADAR_FINGERPRINTS_DIR", tmp_dir.join("fingerprints").to_str().unwrap())
        .arg("--mode")
        .arg("sim")
        .arg("--test-script")
        .arg(&script_file)
        .arg("--test-out")
        .arg(&out_dir)
        .arg("--port")
        .arg(port.to_string())
        .stdin(Stdio::null())
        .spawn()
        .expect("Failed to spawn passiveradar binary");

    let _child_guard = KillOnDrop(child);
    thread::sleep(Duration::from_millis(600));

    let mut last_err: Option<String> = None;
    let addr: std::net::SocketAddr = format!("127.0.0.1:{}", port).parse().unwrap();
    let ws_url = format!("ws://127.0.0.1:{}", port);
    for _ in 0..10 {
        match std::net::TcpStream::connect_timeout(&addr, Duration::from_millis(250)) {
            Ok(stream) => {
                let _ = stream.set_read_timeout(Some(Duration::from_millis(500)));
                let _ = stream.set_write_timeout(Some(Duration::from_millis(100)));
                
                match tungstenite::client(&ws_url, stream) {
                    Ok((mut socket, _)) => {
                        for (request, expected_substring) in steps {
                            let req_text = serde_json::to_string(&request).unwrap();
                            if let Err(e) = socket.send(Message::Text(req_text.into())) {
                                panic!("Send error in compound test: {:?}", e);
                            }

                            let mut response_found = false;
                            let mut consecutive_would_block = 0;
                            for _ in 0..1000 {
                                match socket.read() {
                                    Ok(Message::Text(text)) => {
                                        consecutive_would_block = 0;
                                        if !text.contains("constellation_points") {
                                            eprintln!("Received text: {}", text);
                                        } else {
                                            eprintln!("Received telemetry ({} bytes)", text.len());
                                        }
                                        if text.contains(expected_substring) {
                                            response_found = true;
                                            break;
                                        }
                                    }
                                    Ok(_) => {
                                        consecutive_would_block = 0;
                                    }
                                    Err(e) => {
                                        let err_str = format!("{:?}", e);
                                        if err_str.contains("WouldBlock") || err_str.contains("TimedOut") || err_str.contains("timed out") {
                                            consecutive_would_block += 1;
                                            if consecutive_would_block > 10 {
                                                break;
                                            }
                                            thread::sleep(Duration::from_millis(20));
                                        } else {
                                            eprintln!("Read error: {}", err_str);
                                            break;
                                        }
                                    }
                                }
                            }

                            if !response_found {
                                if let Ok(entries) = fs::read_dir(&out_dir) {
                                    for entry in entries {
                                        if let Ok(entry) = entry {
                                            if let Ok(content) = fs::read_to_string(entry.path()) {
                                                if content.contains(expected_substring) {
                                                    response_found = true;
                                                    break;
                                                }
                                            }
                                        }
                                    }
                                }
                            }

                            if !response_found {
                                panic!("Failed to find expected substring {:?} in compound test step", expected_substring);
                            }
                        }
                        let _ = fs::remove_dir_all(&tmp_dir);
                        return;
                    }
                    Err(e) => {
                        last_err = Some(format!("Handshake error: {:?}", e));
                    }
                }
            }
            Err(e) => {
                last_err = Some(format!("Tcp connect error: {:?}", e));
            }
        }
        thread::sleep(Duration::from_millis(300));
    }
    panic!("Failed to verify compound WebSocket server response: {:?}", last_err);
}


// =========================================================================
// TIER 1: FEATURE COVERAGE
// =========================================================================

// WebSocket Grouped Tests
#[test]
fn test_gain_ws_compound() {
    run_ws_compound_test("TICK 500\nDUMP frame.txt", vec![
        (json!({"command": "set_sdr_settings", "gain": 15.0}), "\"gain\": 15.0"),
        (json!({"command": "set_sdr_settings", "gain": 999.0}), "\"error\": \"Gain value out of bounds\""),
        (json!({"command": "set_sdr_settings", "gain": -5.0}), "\"error\": \"Gain value out of bounds\""),
        (json!({"command": "set_sdr_settings", "gain": 12.3456}), "\"gain\": 12.3"),
        (json!({"command": "set_sdr_settings", "gain": "garbage"}), "\"error\": \"Invalid arguments\""),
        (json!({"command": "set_sdr_settings", "gain": 10.0}), "\"gain\": 10.0"),
        (json!({"command": "set_sdr_settings", "gain": 12.0}), "Gain: 12.0"), // sync
    ]);
}

#[test]
fn test_dc_block_ws_compound() {
    run_ws_compound_test("TICK 500\nDUMP frame.txt", vec![
        (json!({"command": "set_sdr_settings", "dc_block": false}), "\"dc_block\": false"),
        (json!({"command": "InjectDcOffset", "value": 1000.0}), "\"dc_offset_filter\": \"saturated\""),
        (json!({"command": "SetDcFilterAlpha", "alpha": 0.0001}), "\"alpha\": 0.0001"),
        (json!({"command": "InjectDcOffset", "value": 0.0}), "\"dc_offset\": 0.0"),
        (json!({"command": "SetDcFilterAlpha", "alpha": 1.5}), "\"error\": \"Alpha out of bounds\""),
        (json!({"command": "set_sdr_settings", "dc_block": true}), "DC Block: ON"), // sync
    ]);
}

#[test]
fn test_spectrogram_ws_compound() {
    run_ws_compound_test("TICK 500", vec![
        (json!({"command": "GetWaterfall"}), "\"waterfall\":"),
        (json!({"command": "SetWaterfallPower", "min": -100, "max": 0}), "\"waterfall_min\": -100"),
        (json!({"command": "InjectSignalAmplitude", "value": 0.0}), "\"waterfall_signal\": 0.0"),
        (json!({"command": "SetWaterfallPower", "min": -99999, "max": 99999}), "\"error\": \"Invalid bounds\""),
    ]);
}

#[test]
fn test_constellation_ws_compound() {
    run_ws_compound_test("TICK 500", vec![
        (json!({"command": "GetConstellation"}), "\"constellation_points\":"),
        (json!({"command": "SetConstellationRate", "fps": 30}), "\"fps\": 30"),
        (json!({"command": "InjectOutlierIQ", "i": 1000.0, "q": -1000.0}), "\"outliers_filtered\": true"),
        (json!({"command": "SetIQDensity", "points": 10000}), "\"points\": 10000"),
        (json!({"command": "InjectIQPoint", "i": 0.0, "q": 0.0}), "\"point_added\": true"),
    ]);
}

#[test]
fn test_micro_doppler_ws_compound() {
    run_ws_compound_test("TICK 500", vec![
        (json!({"command": "SelectTarget", "id": 42}), "\"selected_target\": 42"),
        (json!({"command": "SetDopplerNoiseFloor", "db": -80.0}), "\"doppler_noise_floor\": -80"),
        (json!({"command": "InjectTargetVelocity", "id": 42, "velocity": 3400.0}), "\"supersonic_warning\": true"),
        (json!({"command": "SetDopplerFFT", "size": 999}), "\"error\": \"Invalid FFT size\""),
    ]);
}

#[test]
fn test_aligner_ws_compound() {
    run_ws_compound_test("TICK 500", vec![
        (json!({"command": "GetTowerBearings"}), "\"tower_bearings\":"),
        (json!({"command": "CalibrateAntenna", "angle": 120.0}), "\"calibrated\": true"),
    ]);
}

#[test]
fn test_hacker_ws_compound() {
    let long_cmd = "A".repeat(5000);
    run_ws_compound_test("TICK 500\nDUMP frame.txt", vec![
        (json!({"command": "hacker_cmd", "payload": "jam --freq 1090"}), "\"jamming\": \"active\""),
        (json!({"command": "hacker_cmd", "payload": "spoof --id 9999"}), "\"spoofing\": 9999"),
        (json!({"command": "hacker_cmd", "payload": "sysinfo"}), "\"system_status\":"),
        (json!({"command": "hacker_cmd", "payload": "scan"}), "\"frequencies\":"),
        (json!({"command": "hacker_cmd", "payload": long_cmd}), "\"error\": \"Buffer overflow\""),
        (json!({"command": "hacker_cmd", "payload": "spoof --id 101 --id 101"}), "\"error\": \"Duplicate spoof ID\""),
        (json!({"command": "hacker_cmd", "payload": "spoof --speed 400000000"}), "\"error\": \"Superluminal velocity disallowed\""),
        (json!({"command": "hacker_cmd", "payload": "ping"}), "\"status\": \"pong\""),
        (json!({"command": "hacker_cmd", "payload": "not_a_valid_command"}), "\"error\": \"Unknown command\""),
        (json!({"command": "hacker_cmd", "payload": "mitigate --spoof"}), "Spoof mitigation applied"),
    ]);
}

#[test]
fn test_speech_ws_compound() {
    run_ws_compound_test("TICK 500", vec![
        (json!({"command": "SayText", "text": "<script>alert(1)</script>"}), "\"sanitized\": true"),
    ]);
}

// TUI Tests

// Feature 1: Gain slider (SDR gain control)
#[test]
fn test_tier1_gain_increment_tui() {
    run_tui_test(240, 40, "KEY ]\nTICK 1\nDUMP frame.txt", &["Gain: 6.5"], &[]);
}
#[test]
fn test_tier1_gain_decrement_tui() {
    run_tui_test(240, 40, "KEY [\nTICK 1\nDUMP frame.txt", &["Gain: 5.5"], &[]);
}
#[test]
fn test_tier1_gain_max_limit() {
    run_tui_test(240, 40, "KEY ]\nKEY ]\nKEY ]\nKEY ]\nKEY ]\nKEY ]\nKEY ]\nKEY ]\nKEY ]\nKEY ]\nTICK 1\nDUMP frame.txt", &["Gain: 10.0"], &[]);
}

// Feature 2: DC block (SDR DC offset blocking filter)
#[test]
fn test_tier1_dc_block_toggle_on_tui() {
    run_tui_test(240, 40, "KEY d\nTICK 1\nDUMP frame.txt", &["DC Block: ON"], &[]);
}
#[test]
fn test_tier1_dc_block_toggle_off_tui() {
    run_tui_test_toggle(
        240, 40,
        "KEY d\nTICK 1\nDUMP frame_before.txt\nTICK 1\nKEY d\nTICK 1\nDUMP frame.txt",
        &["DC Block: OFF |"],
        &["DC Block: ON |"],
        &["DC Block: OFF |"],
    );
}

// Feature 3: Spectrogram (RF Signal Waterfall canvas)
#[test]
fn test_tier1_spectrogram_toggle_off_tui() {
    run_tui_test_toggle(
        240, 40,
        "TICK 1\nDUMP frame_before.txt\nTICK 1\nKEY w\nTICK 1\nDUMP frame.txt",
        &["Waterfall"],
        &[],
        &["Waterfall", "Spectrogram"],
    );
}
#[test]
fn test_tier1_spectrogram_visual_symbols() {
    run_tui_test(240, 40, "TICK 1\nDUMP frame.txt", &["░", "▒", "▓", "█"], &[]);
}
#[test]
fn test_tier1_spectrogram_resize_width() {
    run_tui_test(80, 40, "TICK 1\nDUMP frame.txt", &["Doppler"], &[]);
}

// Feature 4: IQ Constellation (IQ Constellation diagram)
#[test]
fn test_tier1_constellation_tui_rendering() {
    run_tui_test(240, 40, "TICK 1\nDUMP frame.txt", &["Constellation Diagram", "IQ Scope"], &[]);
}
#[test]
fn test_tier1_constellation_accuracy() {
    run_tui_test(240, 40, "TICK 1\nDUMP frame.txt", &["Centroid", "IQ:"], &[]);
}
#[test]
fn test_tier1_constellation_toggle_off() {
    run_tui_test_toggle(
        240, 40,
        "TICK 1\nDUMP frame_before.txt\nTICK 1\nKEY c\nTICK 1\nDUMP frame.txt",
        &["Constellation Diagram"],
        &[],
        &["Constellation Diagram"],
    );
}

// Feature 5: Micro-Doppler (JEM detail panel)
#[test]
fn test_tier1_micro_doppler_tui_inspect() {
    run_tui_test(240, 40, "TICK 15\nKEY down\nKEY enter\nTICK 1\nDUMP frame.txt", &["Micro-Doppler Scope", "JEM Analysis"], &[]);
}
#[test]
fn test_tier1_micro_doppler_scale_toggle() {
    run_tui_test(240, 40, "TICK 15\nKEY down\nKEY enter\nKEY v\nTICK 1\nDUMP frame.txt", &["Scale: +/-"], &[]);
}
#[test]
fn test_tier1_micro_doppler_empty_unselected() {
    run_tui_test(240, 40, "KEY esc\nTICK 1\nDUMP frame.txt", &["No Target Selected"], &["JEM Analysis"]);
}

// Feature 6: Antenna Aligner (Polar antenna alignment scope)
#[test]
fn test_tier1_aligner_tui_rendering() {
    run_tui_test(240, 40, "TICK 1\nDUMP frame.txt", &["Antenna Alignment Scope", "Compass Grid"], &[]);
}
#[test]
fn test_tier1_aligner_bearing_calc() {
    run_tui_test_with_args(240, 40, "TICK 1\nDUMP frame.txt", &["Bearing: 45.0°", "Alignment Scope"], &[], &["--heading", "45.0"]);
}
#[test]
fn test_tier1_aligner_peak_detection() {
    run_tui_test(240, 40, "TICK 1\nDUMP frame.txt", &["Peak Signal Strength"], &[]);
}
#[test]
fn test_tier1_aligner_toggle_off() {
    run_tui_test_toggle(
        240, 40,
        "TICK 1\nDUMP frame_before.txt\nTICK 1\nKEY a\nTICK 1\nDUMP frame.txt",
        &["Antenna Alignment Scope"],
        &[],
        &["Antenna Alignment Scope"],
    );
}
#[test]
fn test_tier1_logs_toggle_off() {
    run_tui_test_toggle(
        240, 40,
        "TICK 1\nDUMP frame_before.txt\nTICK 1\nKEY l\nTICK 1\nDUMP frame.txt",
        &["System Events Log"],
        &[],
        &["System Events Log"],
    );
}

// Feature 7: Hacker Console (Interactive retro monospaced terminal)
#[test]
fn test_tier1_hacker_toggle_tui() {
    run_tui_test(240, 40, "KEY h\nTICK 1\nDUMP frame.txt", &["Hacker Terminal", "passiveradar_hacker>"], &[]);
}

// Feature 8: CRT/Audio Aesthetics (CRT scanlines, audio hum, Doppler beeps, speech announcements)
#[test]
fn test_tier1_crt_toggle_indicator() {
    run_tui_test(240, 40, "KEY x\nTICK 1\nDUMP frame.txt", &["CRT: ON"], &[]);
}
#[test]
fn test_tier1_crt_meteor_shake() {
    run_tui_test(240, 40, "KEY m\nTICK 1\nDUMP frame.txt", &["METEOR EVENT DETECTED", "[SCREEN SHAKE]"], &[]);
}
#[test]
fn test_tier1_audio_hum_indicator() {
    run_tui_test(240, 40, "TICK 1\nDUMP frame.txt", &["Hum: 60Hz"], &[]);
}
#[test]
fn test_tier1_audio_doppler_beep() {
    run_tui_test(240, 40, "TICK 1\nDUMP frame.txt", &["Audio: Beep ON"], &[]);
}
#[test]
fn test_tier1_audio_speech_lock() {
    run_tui_test(240, 40, "TICK 1\nDUMP frame.txt", &["Speech Synthesizer: READY"], &[]);
}

// =========================================================================
// TIER 2: BOUNDARY & CORNER CASES
// =========================================================================

#[test]
fn test_tier2_dc_block_rapid_toggling() {
    run_tui_test(240, 40, "KEY d\nKEY d\nKEY d\nKEY d\nKEY d\nKEY d\nTICK 1\nDUMP frame.txt", &["DC Block: OFF"], &[]);
}

#[test]
fn test_tier2_spectrogram_height_collapse() {
    run_tui_test(120, 5, "TICK 1\nDUMP frame.txt", &[], &["Waterfall", "Spectrogram"]);
}
#[test]
fn test_tier2_spectrogram_buffer_wrap() {
    run_tui_test(240, 40, "TICK 50\nDUMP frame.txt", &["Waterfall"], &[]);
}
#[test]
fn test_tier2_spectrogram_zero_towers() {
    run_tui_test_with_args(240, 40, "TICK 1\nDUMP frame.txt", &["No Signal"], &[], &["--no-towers"]);
}

#[test]
fn test_tier2_constellation_empty() {
    run_tui_test_with_args(240, 40, "TICK 1\nDUMP frame.txt", &["Empty Constellation"], &[], &["--no-signal"]);
}
#[test]
fn test_tier2_constellation_width_collapse() {
    run_tui_test(40, 40, "TICK 1\nDUMP frame.txt", &[], &["Constellation Diagram"]);
}

#[test]
fn test_tier2_micro_doppler_rapid_switching() {
    run_tui_test(240, 40, "TICK 15\nKEY down\nKEY enter\nKEY down\nKEY enter\nKEY down\nKEY enter\nTICK 1\nDUMP frame.txt", &["Micro-Doppler Scope"], &[]);
}
#[test]
fn test_tier2_micro_doppler_termination() {
    run_tui_test_with_args(240, 40, "TICK 15\nKEY down\nKEY enter\nTICK 150\nDUMP frame.txt", &["Target Terminated"], &[], &["--mock-target-termination"]);
}
#[test]
fn test_tier2_micro_doppler_unclassified_default() {
    run_tui_test(270, 40, "TICK 15\nKEY down\nKEY enter\nTICK 1\nDUMP frame.txt", &["Class: UNKNOWN"], &[]);
}

#[test]
fn test_tier2_aligner_heading_wrap_positive() {
    run_tui_test_with_args(240, 40, "TICK 1\nDUMP frame.txt", &["Bearing: 90.0°"], &[], &["--heading", "450.0"]);
}
#[test]
fn test_tier2_aligner_heading_wrap_negative() {
    run_tui_test_with_args(240, 40, "TICK 1\nDUMP frame.txt", &["Bearing: 270.0°"], &[], &["--heading", "-90.0"]);
}
#[test]
fn test_tier2_aligner_exact_origin() {
    run_tui_test_with_args(240, 40, "TICK 1\nDUMP frame.txt", &["Overlap Warning"], &[], &["--tower-at-origin"]);
}
#[test]
fn test_tier2_aligner_zero_towers() {
    run_tui_test_with_args(240, 40, "TICK 1\nDUMP frame.txt", &["No Towers in Compass"], &[], &["--no-towers"]);
}
#[test]
fn test_tier2_aligner_many_towers_overlap() {
    run_tui_test_with_args(240, 40, "TICK 1\nDUMP frame.txt", &["Towers: 50+"], &[], &["--many-towers"]);
}

#[test]
fn test_tier2_crt_low_resolution() {
    run_tui_test(20, 10, "KEY x\nTICK 1\nDUMP frame.txt", &["CRT"], &[]);
}
#[test]
fn test_tier2_crt_rapid_shake() {
    run_tui_test(240, 40, "KEY x\nKEY m\nKEY m\nKEY m\nTICK 1\nDUMP frame.txt", &["CRT: ON", "[SCREEN SHAKE]"], &[]);
}
#[test]
fn test_tier2_audio_missing_hardware() {
    run_tui_test_with_args(240, 40, "TICK 1\nDUMP frame.txt", &["Audio: Fallback Driver"], &[], &["--mock-no-audio"]);
}
#[test]
fn test_tier2_audio_100_targets_clipping() {
    run_tui_test_with_args(240, 40, "TICK 1\nDUMP frame.txt", &["Audio Hum: Clipped"], &[], &["--max-targets"]);
}

// =========================================================================
// TIER 3: CROSS-FEATURE COMBINATIONS
// =========================================================================

#[test]
fn test_tier3_combo_1() {
    run_tui_test(240, 40, "TICK 1\nDUMP frame.txt", &["Gain: 5.0", "DC Block: OFF", "CRT: OFF"], &["Jammer Active", "JEM Analysis"]);
}

#[test]
fn test_tier3_combo_2() {
    run_tui_test(240, 40, "TICK 15\nKEY ]\nKEY d\nKEY h\nKEY down\nKEY enter\nKEY x\nTICK 1\nDUMP frame.txt", &["Gain: 6.0", "DC Block: ON", "Hacker Terminal", "Micro-Doppler Scope", "CRT: ON"], &[]);
}

#[test]
fn test_tier3_combo_3() {
    run_tui_test(240, 40, "KEY d\nKEY h\nKEY x\nTICK 1\nDUMP frame.txt", &["Gain: 5.0", "DC Block: ON", "Hacker Terminal", "CRT: ON"], &["JEM Analysis"]);
}

#[test]
fn test_tier3_combo_4() {
    run_tui_test(240, 40, "TICK 15\nKEY ]\nKEY down\nKEY enter\nTICK 1\nDUMP frame.txt", &["Gain: 6.0", "DC Block: OFF", "Micro-Doppler Scope", "CRT: OFF"], &["Hacker Terminal"]);
}

#[test]
fn test_tier3_combo_5() {
    run_tui_test(240, 40, "TICK 15\nKEY h\nKEY down\nKEY enter\nKEY x\nTICK 1\nDUMP frame.txt", &["Gain: 5.0", "DC Block: OFF", "Hacker Terminal", "Micro-Doppler Scope", "CRT: ON"], &[]);
}

#[test]
fn test_tier3_combo_6() {
    run_tui_test(240, 40, "KEY ]\nKEY d\nTICK 1\nDUMP frame.txt", &["Gain: 6.0", "DC Block: ON", "CRT: OFF"], &["Hacker Terminal", "JEM Analysis"]);
}

#[test]
fn test_tier3_combo_7() {
    run_tui_test(240, 40, "KEY ]\nKEY h\nKEY x\nTICK 1\nDUMP frame.txt", &["Gain: 6.0", "DC Block: OFF", "Hacker Terminal", "CRT: ON"], &["JEM Analysis"]);
}

#[test]
fn test_tier3_combo_8() {
    run_tui_test(240, 40, "TICK 15\nKEY d\nKEY down\nKEY enter\nTICK 1\nDUMP frame.txt", &["Gain: 5.0", "DC Block: ON", "Micro-Doppler Scope", "CRT: OFF"], &["Hacker Terminal"]);
}

// =========================================================================
// TIER 4: REAL-WORLD APPLICATION SCENARIOS
// =========================================================================

#[test]
fn test_tier4_scenario_1_airliner_jamming() {
    run_tui_test(240, 40, "TICK 15\nKEY ]\nKEY d\nKEY h\nKEY down\nKEY enter\nTICK 1\nDUMP frame.txt", &["Gain: 6.0", "DC Block: ON", "Hacker Terminal", "Micro-Doppler Scope"], &[]);
}

#[test]
fn test_tier4_scenario_2_drone_clutter() {
    run_tui_test(240, 40, "TICK 15\nKEY d\nKEY x\nKEY down\nKEY enter\nTICK 1\nDUMP frame.txt", &["DC Block: ON", "CRT: ON", "Micro-Doppler Scope"], &[]);
}

#[test]
fn test_tier4_scenario_3_multi_tower_meteor() {
    run_tui_test(240, 40, "KEY m\nTICK 1\nDUMP frame.txt", &["METEOR EVENT DETECTED", "Antenna Alignment Scope", "Compass Grid"], &[]);
}

// =========================================================================
// SDR Settings Bounds & Types Validation (Adversarial Hardening)
// =========================================================================

#[test]
fn test_adversarial_gain_nan() {
    run_ws_compound_test("TICK 500", vec![
        (
            json!({"command": "set_sdr_settings", "gain": std::f64::NAN}),
            "\"error\": \"Gain value out of bounds\""
        )
    ]);
}

#[test]
fn test_adversarial_gain_infinity() {
    run_ws_compound_test("TICK 500", vec![
        (
            json!({"command": "set_sdr_settings", "gain": std::f64::INFINITY}),
            "\"error\": \"Gain value out of bounds\""
        ),
        (
            json!({"command": "set_sdr_settings", "gain": std::f64::NEG_INFINITY}),
            "\"error\": \"Gain value out of bounds\""
        )
    ]);
}

#[test]
fn test_adversarial_dc_alpha_nan() {
    run_ws_compound_test("TICK 500", vec![
        (
            json!({"command": "SetDcFilterAlpha", "alpha": std::f64::NAN}),
            "\"error\": \"Alpha out of bounds\""
        )
    ]);
}

#[test]
fn test_adversarial_dc_offset_nan() {
    run_ws_compound_test("TICK 500", vec![
        (
            json!({"command": "InjectDcOffset", "value": std::f64::NAN}),
            "\"error\": \"Invalid arguments\""
        )
    ]);
}

// =========================================================================
// Terminal Command Parser Safety Limits
// =========================================================================

#[test]
fn test_adversarial_hacker_spoof_speed_nan() {
    run_ws_compound_test("TICK 500", vec![
        (
            json!({"command": "hacker_cmd", "payload": "spoof --id 1234 --speed NaN"}),
            "\"error\": \"Superluminal velocity disallowed\""
        )
    ]);
}

#[test]
fn test_adversarial_hacker_spoof_speed_negative() {
    run_ws_compound_test("TICK 500", vec![
        (
            json!({"command": "hacker_cmd", "payload": "spoof --id 1234 --speed -150.0"}),
            "\"error\": \"Invalid speed bounds\""
        )
    ]);
}

#[test]
fn test_adversarial_hacker_spoof_id_overflow() {
    run_ws_compound_test("TICK 500", vec![
        (
            json!({"command": "hacker_cmd", "payload": "spoof --id 999999999999999999999999 --speed 120.0"}),
            "\"error\": \"Invalid target ID\""
        )
    ]);
}

#[test]
fn test_adversarial_hacker_spoof_missing_id_argument() {
    run_ws_compound_test("TICK 500", vec![
        (
            json!({"command": "hacker_cmd", "payload": "spoof --id"}),
            "\"error\": \"Invalid arguments\""
        )
    ]);
}

#[test]
fn test_adversarial_hacker_cmd_empty_payload() {
    run_ws_compound_test("TICK 500", vec![
        (
            json!({"command": "hacker_cmd", "payload": "   "}),
            "\"error\": \"Unknown command\""
        )
    ]);
}

// =========================================================================
// Polar Alignment Scope
// =========================================================================

#[test]
fn test_adversarial_antenna_calibrate_nan() {
    run_ws_compound_test("TICK 500", vec![
        (
            json!({"command": "CalibrateAntenna", "angle": std::f64::NAN}),
            "\"error\": \"Invalid angle bounds\""
        )
    ]);
}

// =========================================================================
// Micro-Doppler Spectrum (JEM) Validation
// =========================================================================

#[test]
fn test_adversarial_doppler_fft_size_sync() {
    run_ws_compound_test("TICK 500", vec![
        (
            json!({"command": "SetDopplerFFT", "size": 512}),
            "\"fft_size\": 512"
        )
    ]);
}

// =========================================================================
// Target Spoofing Queue Limits (DoS Prevention)
// =========================================================================

#[test]
fn test_adversarial_spoof_queue_overflow() {
    let mut steps = Vec::new();
    for i in 0..25 {
        steps.push((
            json!({"command": "hacker_cmd", "payload": format!("spoof --id {} --speed 200.0", 5000 + i)}),
            if i < 20 { "spoofing" } else { "error" }
        ));
    }
    run_ws_compound_test("TICK 10000", steps);
}
