use num_complex::Complex;

/// Cohomological Anomaly Detector.
#[derive(Debug, Clone)]
pub struct CohomologyFirewall {
    pub dimension: usize,
    pub lag: usize,
    pub epsilon: f32,
}

impl CohomologyFirewall {
    pub fn new(dimension: usize, lag: usize, epsilon: f32) -> Self {
        Self {
            dimension,
            lag,
            epsilon,
        }
    }

    /// Embeds a sequence of complex samples into a higher-dimensional real space.
    /// Dimension d, lag l. Returns a Vec of vectors of size 2*d.
    /// Uniformly downsamples to a maximum of 256 points to guarantee O(V^3) computation safety.
    pub fn delay_embed(&self, samples: &[Complex<f32>]) -> Vec<Vec<f32>> {
        let n = samples.len();
        let span = (self.dimension - 1) * self.lag;
        if n <= span {
            return Vec::new();
        }

        let total_embeddings = n - span;
        let mut embeddings = Vec::with_capacity(total_embeddings);
        for i in 0..total_embeddings {
            let mut pt = Vec::with_capacity(2 * self.dimension);
            for d in 0..self.dimension {
                let idx = i + d * self.lag;
                pt.push(samples[idx].re);
                pt.push(samples[idx].im);
            }
            embeddings.push(pt);
        }

        // Apply uniform downsampling if embeddings exceed 256 points
        let max_points = 256;
        if embeddings.len() > max_points {
            let mut downsampled = Vec::with_capacity(max_points);
            let total = embeddings.len();
            for i in 0..max_points {
                let idx = (i * (total - 1)) / (max_points - 1);
                downsampled.push(embeddings[idx].clone());
            }
            embeddings = downsampled;
        }

        embeddings
    }

    /// Approximates the 1st Betti number (b1) of the Vietoris-Rips complex
    /// generated by the delay-embedded points at filtration scale epsilon.
    /// Computes the exact connected components (b0) to refine the Betti-1 estimation: b1 = E - V - T + b0.
    pub fn compute_b1(&self, points: &[Vec<f32>]) -> f32 {
        let v = points.len();
        if v < 3 {
            return 0.0;
        }

        // Compute pairwise distances
        let mut dist = vec![vec![0.0f32; v]; v];
        for i in 0..v {
            for j in (i + 1)..v {
                let mut sum_sq = 0.0;
                for k in 0..points[i].len() {
                    sum_sq += (points[i][k] - points[j][k]).powi(2);
                }
                let d = sum_sq.sqrt();
                dist[i][j] = d;
                dist[j][i] = d;
            }
        }

        // Count edges (1-simplices)
        let mut e = 0;
        let mut adj = vec![vec![false; v]; v];
        for i in 0..v {
            for j in (i + 1)..v {
                if dist[i][j] <= self.epsilon {
                    e += 1;
                    adj[i][j] = true;
                    adj[j][i] = true;
                }
            }
        }

        // Count triangles (2-simplices)
        let mut t = 0;
        for i in 0..v {
            for j in (i + 1)..v {
                if adj[i][j] {
                    for k in (j + 1)..v {
                        if adj[i][k] && adj[j][k] {
                            t += 1;
                        }
                    }
                }
            }
        }

        // Compute actual b0 (connected components) of the adjacency graph via DFS stack
        let mut visited = vec![false; v];
        let mut b0 = 0;
        for i in 0..v {
            if !visited[i] {
                b0 += 1;
                let mut stack = vec![i];
                visited[i] = true;
                while let Some(curr) = stack.pop() {
                    for neighbor in 0..v {
                        if adj[curr][neighbor] && !visited[neighbor] {
                            visited[neighbor] = true;
                            stack.push(neighbor);
                        }
                    }
                }
            }
        }

        // Euler characteristic formula approximation of b1: chi = V - E + T = b0 - b1
        // b1 = E - V - T + b0
        let b1 = (e as isize) - (v as isize) - (t as isize) + b0;
        if b1 < 0 {
            0.0
        } else {
            b1 as f32
        }
    }

    /// Computes the topological entropy of the distance matrix.
    /// High entropy indicates structural distortion (anomaly).
    pub fn compute_topological_entropy(&self, points: &[Vec<f32>]) -> f32 {
        let v = points.len();
        if v < 2 {
            return 0.0;
        }

        let mut distances = Vec::new();
        for i in 0..v {
            for j in (i + 1)..v {
                let mut sum_sq = 0.0;
                for k in 0..points[i].len() {
                    sum_sq += (points[i][k] - points[j][k]).powi(2);
                }
                distances.push(sum_sq.sqrt());
            }
        }

        // Compute histogram/distribution of distances
        let n_bins = 10;
        let mut bins = vec![0; n_bins];
        let max_d = distances.iter().cloned().fold(0.0f32, f32::max);
        if max_d == 0.0 {
            return 0.0;
        }

        for &d in &distances {
            let mut bin_idx = (d / max_d * (n_bins as f32)) as usize;
            if bin_idx >= n_bins {
                bin_idx = n_bins - 1;
            }
            bins[bin_idx] += 1;
        }

        let mut entropy = 0.0f32;
        let total = distances.len() as f32;
        for &count in &bins {
            if count > 0 {
                let p = (count as f32) / total;
                entropy -= p * p.ln();
            }
        }
        entropy
    }
}
